mod growth;
mod integrated;
mod placement;
mod ports;

pub use growth::{
    FacilityGrowthComponent, FacilityGrowthDiagnostic, FacilityGrowthPhase,
    FacilityGrowthPlanReport, plan_facility_growth,
};

pub use integrated::{
    BOTTOM_UP_EXPERIMENT_SCHEMA_VERSION, BOTTOM_UP_RUNG_SCHEMA_VERSION, BottomUpExperimentReport,
    BottomUpRungKind, BottomUpRungOutcome, BottomUpRungReport, BottomUpRungWitness,
    BottomUpSearchProfile, BottomUpSearchSpaceProfile, BottomUpSemanticCertificate,
    BottomUpTerminationReason, EndpointClearancePropagationStatistics,
    EndpointClearanceSchedulingPriority, FacilityEndpointPlacement, FacilityGeometryPlacement,
    FacilityGeometryWitness, FacilityPortPlacement, FacilityPortsWitness, diagnose_bottom_up_rung,
};
pub use integrated::{
    BOUNDARY_CELL_WIDTH_SENSITIVITY_SCHEMA_VERSION, BoundaryCellWidthCaseReport,
    BoundaryCellWidthSensitivityReport, CONNECTIVITY_WITNESS_DIAGNOSIS_SCHEMA_VERSION,
    CUMULATIVE_EXACT_DIMENSION_SWEEP_SCHEMA_VERSION,
    CUMULATIVE_FACILITY_COORDINATE_PARTITION_SCHEMA_VERSION,
    CUMULATIVE_FACILITY_PORT_PARTITION_SCHEMA_VERSION,
    CUMULATIVE_FACILITY_ROTATION_PARTITION_SCHEMA_VERSION,
    CUMULATIVE_FACILITY_STATE_PARTITION_SCHEMA_VERSION, CUMULATIVE_SCC_GROWTH_SCHEMA_VERSION,
    ConnectivityWitnessCaseKind, ConnectivityWitnessCaseReport, ConnectivityWitnessDiagnosisReport,
    ConnectivityWitnessStateScale, CumulativeExactDimensionSweepReport,
    CumulativeFacilityCoordinatePartitionReport, CumulativeFacilityPortPartitionReport,
    CumulativeFacilityRotationPartitionReport, CumulativeFacilityStatePartitionReport,
    CumulativeSccGrowthReport, DiagnosticSearchMode,
    ENDPOINT_CONTINUATION_PARTITION_SCHEMA_VERSION, ENDPOINT_SOURCE_ONLY_CONTROL_SCHEMA_VERSION,
    EXACT_ABLATION_MATRIX_SCHEMA_VERSION, EXACT_DIMENSION_PARTITION_SCHEMA_VERSION,
    EXTERNAL_BOUNDARY_CELL_PARTITION_SCHEMA_VERSION,
    EXTERNAL_BOUNDARY_KEY_LEGAL_SUPPORT_AB_SCHEMA_VERSION,
    EXTERNAL_BOUNDARY_SIDE_PARTITION_SCHEMA_VERSION, EXTERNAL_CONNECTOR_PORT_DOMAIN_SCHEMA_VERSION,
    EXTERNAL_CONNECTOR_SUBSET_SCHEMA_VERSION, EndpointContinuationCandidate,
    EndpointContinuationCaseReport, EndpointContinuationPartitionReport,
    EndpointSourceOnlyCaseReport, EndpointSourceOnlyControlReport, EndpointSourceRegionEvidence,
    ExactAblationCaseReport, ExactAblationFixation, ExactAblationMatrixReport,
    ExactDimensionCaseDisposition, ExactDimensionCaseOutcome, ExactDimensionLowerBoundsReport,
    ExactDimensionPartitionCaseReport, ExactDimensionSolverStack,
    ExactDimensionUpperBoundImprovement, ExactModelMetrics, ExactObjectiveKind,
    ExactObjectiveStageReport, ExactObjectiveValue, ExactProofStatus, ExactSearchStatistics,
    ExactSolveReport, ExactTerminationReason, ExactUsedDimensionCandidate, ExactValidationStatus,
    ExternalBoundaryCellCaseReport, ExternalBoundaryCellPartitionReport,
    ExternalBoundaryKeyCommonModelContract, ExternalBoundaryKeyLegalSupportAbReport,
    ExternalBoundaryKeyNetworkContract, ExternalBoundaryKeyRootComparison,
    ExternalBoundaryKeyRootTotals, ExternalBoundaryKeySolveReport,
    ExternalBoundaryKeyStaticCertificate, ExternalBoundarySideCaseReport,
    ExternalBoundarySideDomain, ExternalBoundarySidePartitionReport,
    ExternalConnectorPortDomainClassification, ExternalConnectorPortDomainReport,
    ExternalConnectorRequirementDescriptor, ExternalConnectorSubsetReport,
    FACTORED_ENDPOINT_COMPARISON_SCHEMA_VERSION, FACTORED_NETWORK_DECOMPOSITION_SCHEMA_VERSION,
    FACTORED_REQUIREMENT_DECOMPOSITION_SCHEMA_VERSION, FacilityCoordinateCaseDisposition,
    FacilityCoordinateCaseReport, FacilityPortAssignment, FacilityPortDomainReport,
    FacilityPortPartitionCaseReport, FacilityRotationPartitionCaseReport,
    FacilityStatePartitionCaseReport, FactoredEndpointComparisonReport,
    FactoredNetworkDecompositionReport, FactoredNetworkSubsetCaseReport,
    FactoredRequirementDecompositionReport, FactoredRequirementSubsetCaseReport,
    GUARDED_CORE_BOUNDARY_CENSUS_SCHEMA_VERSION, GUARDED_CORE_INITIAL_GATE_SCHEMA_VERSION,
    GuardedCoreAcceptedFixture, GuardedCoreBoundaryCensusCase, GuardedCoreBoundaryCensusReport,
    GuardedCoreBoundaryCensusRootStatus, GuardedCoreBoundaryCensusStatus,
    GuardedCoreInitialGateReport, GuardedCoreInitialGateStatus, GuardedCoreReplayReport,
    GuardedCoreReplayStatus, GuardedCoreSequentialShrinkReport, GuardedCoreSequentialShrinkStatus,
    GuardedCoreShrinkAttempt, GuardedItemIntersectionObservation, INTEGRATED_LAYOUT_SCHEMA_VERSION,
    IntegratedLayoutDiagnostic, IntegratedLayoutPhase, IntegratedLayoutReport,
    IntegratedLayoutStatus, LayerGridAnalyzerRuntime,
    MATERIAL_JUNCTION_CONTINUATION_SCHEMA_VERSION, MATERIAL_ROW5_SEPARATOR_SCHEMA_VERSION,
    MATERIAL_SEPARATOR_CUT_SCHEMA_VERSION, MaterialJunctionCaseReport,
    MaterialJunctionContinuationReport, MaterialRow5SeparatorCaseReport,
    MaterialRow5SeparatorReport, MaterialSeparatorCaseReport, MaterialSeparatorCutReport,
    PARALLEL_EXACT_DIMENSION_SWEEP_SCHEMA_VERSION, PHASE2_REFERENCE_ABLATION_SCHEMA_VERSION,
    PHYSICAL_OCCUPANCY_PROBE_SCHEMA_VERSION, POSSIBLE_GRAPH_CONNECTIVITY_DIAGNOSIS_SCHEMA_VERSION,
    PRIOR_INPUT_PAIR_ROOT_SNAPSHOT_SCHEMA_VERSION, PRIOR_INPUT_PORT_CONTROLS_SCHEMA_VERSION,
    PRIOR_INPUT_PORT_PAIR_PORTFOLIO_SCHEMA_VERSION, PRIOR_PORT_SUBSET_ABLATION_SCHEMA_VERSION,
    PRIOR_SOURCE_PORT_PORTFOLIO_SCHEMA_VERSION, PRIOR_TERMINAL_COMPLETION_PORTFOLIO_SCHEMA_VERSION,
    PRIOR_TERMINAL_PAIR_VALUE_PORTFOLIO_SCHEMA_VERSION, ParallelExactDimensionCaseReport,
    ParallelExactDimensionSweepReport, PartitionCaseModelScale, Phase2ReferenceAblationCaseReport,
    Phase2ReferenceAblationKind, Phase2ReferenceAblationReport, PhysicalOccupancyCaseReport,
    PhysicalOccupancyDomainSnapshot, PhysicalOccupancyEncoding, PhysicalOccupancyProbeReport,
    PhysicalOccupancyRestriction, PlacedLogisticsComponent, PossibleGraphConnectivityCaseKind,
    PossibleGraphConnectivityCaseReport, PossibleGraphConnectivityDiagnosisReport,
    PossibleGraphConnectivityRuntime, PossibleGraphConnectivityScale,
    PriorInputPairRootSnapshotReport, PriorInputPortControlCaseReport,
    PriorInputPortControlSuiteReport, PriorInputPortControlsReport, PriorInputPortPairCaseReport,
    PriorInputPortPairPortfolioReport, PriorInputPortProofExclusion, PriorInputPortResidualDomain,
    PriorPortSubsetAblationReport, PriorPortSubsetCaseReport, PriorPortSubsetFacility,
    PriorSourcePortCaseReport, PriorSourcePortParentReport, PriorSourcePortPortfolioReport,
    PriorTerminalCompletionCaseReport, PriorTerminalCompletionDomain,
    PriorTerminalCompletionParentReport, PriorTerminalCompletionPortfolioReport,
    PriorTerminalPairDomain, PriorTerminalPairValueCaseReport,
    PriorTerminalPairValuePortfolioReport, PriorTerminalSubsetPartition,
    PriorTerminalSubsetTerminal, RESIDUAL_FACILITY_PORT_TUPLE_PORTFOLIO_SCHEMA_VERSION,
    RESIDUAL_FACILITY_STATE_ABLATION_SCHEMA_VERSION, ROUTE_CELL_BREAKDOWN_SCHEMA_VERSION,
    ROUTING_STATE_BREAKDOWN_SCHEMA_VERSION, ResidualFacilityPortDomain,
    ResidualFacilityPortFixationObservation, ResidualFacilityPortTupleCaseReport,
    ResidualFacilityPortTuplePortfolioReport, ResidualFacilityStateAblationReport,
    ResidualFacilityStateCaseKind, ResidualFacilityStateCaseReport, RootBooleanDomainCounts,
    RootDomainCardinality, RootDomainSnapshot, RootEndpointContinuationArcSnapshot,
    RootExternalGeometrySnapshot, RootFacilityStateSnapshot, RootFirstDecisionSnapshot,
    RootFlowDomainCounts, RootMaterialJunctionArcSnapshot, RootMaterialJunctionSnapshot,
    RootMaterialNetworkSnapshot, RootMaterialSeparatorArcSnapshot, RootMaterialSeparatorSnapshot,
    RootTerminalDomainSnapshot, RootTransportLayerSnapshot, RootVariableCoverageSnapshot,
    RootVariableFamilySnapshot, RouteCellBreakdownCaseReport, RouteCellBreakdownReport,
    RouteCellLayerScope, RouteCellValueScope, RoutingStateBreakdownCaseReport,
    RoutingStateBreakdownReport, RoutingStateFamily, RoutingStateMatrixKind,
    SEARCH_MODE_DIAGNOSIS_SCHEMA_VERSION, SHARED_LAYER_COMPARISON_SCHEMA_VERSION,
    SearchModeDiagnosisCaseReport, SharedLayerComparisonReport,
    TRANSPORT_TILE_CAP_DIAGNOSIS_SCHEMA_VERSION, TransportNetwork, TransportNetworkEndpoint,
    TransportNetworkSegment, TransportNetworkTerminal, TransportTileCapCaseReport,
    TransportTileCapDiagnosisReport, analyze_integrated_layout_search_space,
    compare_first_integrated_layout_phase_factored_endpoints,
    compare_first_integrated_layout_phase_shared_layer,
    decompose_first_integrated_layout_phase_factored_networks,
    decompose_first_integrated_layout_phase_factored_requirements,
    decompose_first_integrated_layout_phase_pair, diagnose_boundary_cell_width_sensitivity,
    diagnose_cumulative_facility_coordinate_partitions,
    diagnose_cumulative_facility_coordinate_partitions_with_local_continuation,
    diagnose_cumulative_facility_port_partitions,
    diagnose_cumulative_facility_port_partitions_with_local_continuation,
    diagnose_cumulative_facility_rotation_partitions,
    diagnose_cumulative_facility_rotation_partitions_with_local_continuation,
    diagnose_cumulative_facility_state_partitions_with_local_continuation,
    diagnose_cumulative_facility_state_partitions_with_prior_overlap_facility_state,
    diagnose_cumulative_transport_tile_caps, diagnose_endpoint_continuation_partition,
    diagnose_endpoint_source_only_control, diagnose_external_boundary_cell_partition,
    diagnose_external_boundary_key_legal_support_ab, diagnose_external_boundary_side_partition,
    diagnose_guarded_core_boundary_census, diagnose_guarded_core_initial_gate,
    diagnose_guarded_core_replay, diagnose_guarded_core_sequential_shrinking,
    diagnose_material_junction_continuation, diagnose_material_row5_separator,
    diagnose_material_separator_cut, diagnose_phase2_connectivity_witness,
    diagnose_phase2_possible_graph_connectivity, diagnose_phase2_reference_ablation,
    diagnose_phase2_route_cell_breakdown, diagnose_phase2_routing_state_breakdown,
    diagnose_prior_input_pair_root_snapshot, diagnose_prior_input_port_controls,
    diagnose_prior_input_port_pair_portfolio, diagnose_prior_port_subset_ablation,
    diagnose_prior_source_port_portfolio, diagnose_prior_terminal_completion_portfolio,
    diagnose_prior_terminal_pair_value_portfolio, diagnose_residual_facility_port_tuple_portfolio,
    diagnose_residual_facility_state_ablation, render_integrated_layout_html,
    render_integrated_layout_html_with_localization, render_physical_occupancy_probe_html,
    run_physical_occupancy_probe, solve_cumulative_scc_growth_v2,
    solve_first_integrated_layout_phase_external_connector_port_domain,
    solve_first_integrated_layout_phase_external_connector_subset,
    solve_first_integrated_layout_phase_fixed_dimensions,
    solve_first_integrated_layout_phase_search_mode,
    solve_first_integrated_layout_phase_with_time_limit, solve_integrated_layout,
    solve_integrated_layout_with_time_limit, sweep_cumulative_integrated_layout_fixed_dimensions,
    sweep_cumulative_integrated_layout_fixed_dimensions_with_local_continuation,
    sweep_cumulative_integrated_layout_fixed_dimensions_with_local_continuation_guarded_intersection_observation,
    sweep_cumulative_integrated_layout_fixed_dimensions_with_local_continuation_guarded_intersection_propagation,
    sweep_first_integrated_layout_phase_fixed_dimensions,
};
pub use integrated::{
    CROSSING_FREE_RESTRICTION_EXPERIMENT_SCHEMA_VERSION, CrossingFreeRestrictionExperimentReport,
    CrossingRestrictionCaseKind, CrossingRestrictionCaseReport, diagnose_crossing_free_restriction,
};
pub use integrated::{
    ENDPOINT_CHANNEL_PROBE_SCHEMA_VERSION, EndpointChannelCaseReport,
    EndpointChannelDomainSnapshot, EndpointChannelEncoding, EndpointChannelEndpointSnapshot,
    EndpointChannelProbeReport, EndpointChannelRestriction, render_endpoint_channel_probe_html,
    run_endpoint_channel_probe,
};
pub use integrated::{
    INTEGRATED_ENDPOINT_CHANNEL_COMPARISON_SCHEMA_VERSION, IntegratedEndpointChannelCaseReport,
    IntegratedEndpointTableScale, run_integrated_endpoint_channel_case,
};
pub use integrated::{
    SCALED_ENDPOINT_CHANNEL_PROBE_SCHEMA_VERSION, ScaledEndpointChannelProbeReport,
    ScaledEndpointDomainSnapshot, ScaledEndpointRestrictionReport,
    ScaledEndpointTerminalDomainSnapshot, ScaledEndpointTerminalScale,
    render_scaled_endpoint_channel_probe_html, run_scaled_endpoint_channel_probe,
};

pub use placement::{
    FacilityPlacement, FacilityPlacementBounds, FacilityPlacementDiagnostic,
    FacilityPlacementReport, FacilityPlacementRequest, FacilityPlacementStatus,
    SUPPORTED_FACILITY_PLACEMENT_SCHEMA_VERSION, solve_facility_placement,
    validate_facility_placement_request,
};
pub use ports::{
    FacilityPortProjectionDiagnostic, FacilityPortProjectionReport, PlacedFacilityPort,
    WorldGridPosition, project_facility_ports,
};
